### ISSUE TITLE
Game crashed while loading a world

### ISSUE THREAD

**Issue by SissyTrashQueen** [owmii/Enemyz#2]
[crash-2019-09-26_18.44.50-server.txt](https://github.com/xieaoDev/Enemyz/files/3660030/crash-2019-09-26_18.44.50-server.txt)

**Comment by owmii** [comment]
What mod version you have?

**Comment by owmii** [comment]
Fixed in version: 0.2.6  [Download](https://www.curseforge.com/minecraft/mc-mods/enemyz/files/2797416)
