### ISSUE TITLE
Ticking entity error

### ISSUE THREAD

**Issue by DatrixTHLK** [owmii/Enemyz#3]
Hi Xieao,

I seem to be getting this error with your mod installed. 
Minecraft: 1.14.4
Forge: 28.1.24 (I know Forge updated to 28.1.39, but there is an error which no mods show up on that version and the game is severly messed up. Another issue entirely.)
Enemyz: 0.2.5
Crash Report: https://gist.github.com/DatrixTHLK/c4be4a0a4e8d51859bd0d112e18881a1
CTD back to desktop is all that happens

**Comment by owmii** [comment]
You're using an old version of Enemyz.
Latest version: [Download](https://www.curseforge.com/minecraft/mc-mods/enemyz/files)

**Comment by DatrixTHLK** [comment]
Thanks for letting me know! I'm surprised how I missed out on your update.
