### ISSUE TITLE
Suggestion: Port to 1.15.X

### ISSUE THREAD

**Issue by dreckz** [owmii/Enemyz#5]
I love this mod and everything about it.  It's small but INCREDIBLY helpful when determining aggro.

This is so helpful in a RPG Modpack I'm developing called _["Treasures of Altera"](https://www.curseforge.com/minecraft/modpacks/treasures-of-altera)_.

I'm planning on making a sequel to this pack and I wanted to incorporate this mod.  A lot of people really found this mod incredibly useful, and would love a port to 1.15.X

Thanks a bunch!
_P.S. Feel free to join the discord.  We have a collective of other modders and content creators too._

**Comment by owmii** [comment]
I will port **Enemyz** after i complete porting **Powah!** mod to 1.15.
Thanks for your suggestion!!
