### ISSUE TITLE
[Crash]  EnemyZ crashing in creative mode

### ISSUE THREAD

**Issue by dreckz** [owmii/Enemyz#6]
MC: 1.15.2
EnemyZ: 0.3.1

Was testing combat damages in creative mode, and the mod lagged very heavily and then it crashed.

Crash report:
[crash-2020-03-04_05.10.04-client.txt](https://github.com/owmii/Enemyz/files/4286955/crash-2020-03-04_05.10.04-client.txt)

**Comment by owmii** [comment]
Enemyz  0.3.1 is for 1.14.4 use Enemyz 1.0.1
